apiVersion: v1
kind: Service
metadata:
  name: sample-external-url-exporter
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: sample-external-url-exporter
  type: ClusterIP
